<?xml version="1.0" encoding="utf-8"?>
<report>
	<activity
		result="Failed"
		duration="4048ms"
		durationms="4048"
		type="root"
		rid="29636a0870dac71"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		user="francoism"
		host="FRANCOISM-PC"
		rxversion="5.4.5.19886"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.34209"
		procarch="32bit"
		language="en-US"
		screenresolution="3840x1200"
		timestamp="14/03/2016 4:26:45 PM"
		timestampiso="2016-03-14T05:26:45"
		timeoutfactor="1"
		module="CloseGenericApp">
		<detail>
			CloseGenericApp
		</detail>
		<varbindings/>
		<item
			timeRelativeToTestSuiteStartTime="00:00.384"
			timeRelativeToTestModuleStartTime="00:00.385"
			timeWallClock="16:26:45"
			time="00:00.384"
			level="Info"
			category="Application">
			<message>
				Closing application containing item 'MainWindow'.
			</message>
			<metainfo
				type="repoitem"
				path="/form[@objectname='MainWindow']"
				fullname="NGTTestAutomationRepository.MainWindow.Self"
				id="cd35dc4ee2304536a27eebaa15eecd9e"
				timeout="30000"
				codefile="c:\Ngt-project\testing\NGTTestAutomation\NGTTestAutomation\CloseGenericApp.cs"
				codeline="82"
				itemindex="0"
				loglvl="Info"/>
		</item>
		<item
			timeRelativeToTestSuiteStartTime="00:04.048"
			timeRelativeToTestModuleStartTime="00:04.049"
			timeWallClock="16:26:49"
			time="00:04.048"
			level="Error"
			category="Module">
			<message>
				Test run was aborted by the user.
			</message>
			<metainfo
				loglvl="Error"/>
		</item>
	</activity>
</report>
